CREATE OR REPLACE FUNCTION insert_dag_node(
    _dag_id INT,
    _task_id VARCHAR(250),
    _execution_date TIMESTAMP WITHOUT TIME ZONE,
    _start_date TIMESTAMP WITHOUT TIME ZONE,
    _end_date TIMESTAMP WITHOUT TIME ZONE,
    _duration INT,
    _state VARCHAR(50),
    _try_number INT,
    _max_tries INT,
    _hostname VARCHAR(100),
    _unixname VARCHAR(100),
    _job_id VARCHAR(250),
    _pool VARCHAR(50),
    _queue VARCHAR(50),
    _priority_weight INT,
    _operator VARCHAR(50),
    _queued_dttm TIMESTAMP WITHOUT TIME ZONE,
    _pid INT,
    _executor_config TEXT,
    _external_executor_id VARCHAR(250),
    _external_job_id VARCHAR(250),
    _dag_run_id INT,
    _pool_slots INT,
    _pool_task_slots INT,
    _pool_weight INT,
    _priority_weight_total INT,
    _operator_id INT,
    _queued_by_job_id INT,
    _queued_by_task_id INT,
    _queued_by_dag_id INT,
    _queued_by_execution_date TIMESTAMP WITHOUT TIME ZONE,
    _queued_by_dag_run_id INT,
    _queued_by_task_instance INT,
    _raw TEXT
)